mapbox_token: "pk.eyJ1Ijoia2ltYWRhY3R5bCIsImEiOiJCYzdNTTR3In0.hkjyGpEFYdSPrVp3e717eA"

collections_dir: collections

collections:
  goose:
    output: true
    permalink: /trails/gooses-gander/stops/:title
  dog:
    output: true
    permalink: /trails/dogs-life/stops/:title
  crow:
    output: true
    permalink: /trails/crow-flies/stops/:title
  bat:
    output: true
    permalink: /trails/bats-eye-view/stops/:title
  horse:
    output: true
    permalink: /trails/horses-tale/stops/:title

defaults:
  - scope:
      path: ""
      type: "bat"
    values:
      layout: "stop"
  - scope:
      path: ""
      type: "crow"
    values:
      layout: "stop"
  - scope:
      path: ""
      type: "dog"
    values:
      layout: "stop"
  - scope:
      path: ""
      type: "goose"
    values:
      layout: "stop"
  - scope:
      path: ""
      type: "horse"
    values:
      layout: "stop"
