mapbox_token: "pk.eyJ1IjoibW9zc2xleWhlcml0YWdlIiwiYSI6ImNqeDFzOGk2MDBjMWgzeW1xYXZ3cjA5eTgifQ.wDNyjGwJn0ZEof6REf-xVQ"

collections_dir: collections

collections:
  goose:
    output: true
    permalink: /trails/gooses-gander/stops/:title
  dog:
    output: true
    permalink: /trails/dogs-life/stops/:title
  crow:
    output: true
    permalink: /trails/crow-flies/stops/:title
  bat:
    output: true
    permalink: /trails/bats-eye-view/stops/:title
  horse:
    output: true
    permalink: /trails/horses-tale/stops/:title

defaults:
  - scope:
      path: ""
      type: "bat"
    values:
      layout: "stop"
      scheme: "bat"
      trail_name: site.data.trails[0].name
  - scope:
      path: ""
      type: "crow"
    values:
      layout: "stop"
      scheme: "crow"
  - scope:
      path: ""
      type: "dog"
    values:
      layout: "stop"
      scheme: "dog"
  - scope:
      path: ""
      type: "goose"
    values:
      layout: "stop"
      scheme: "goose"
      trail_name: "A Goose's Gander"
  - scope:
      path: ""
      type: "horse"
    values:
      layout: "stop"
      scheme: "horse"
