collections_dir: collections
collections:
  goose:
    output: true
    permalink: /trails/gooses-gander/stops/:title
  timeline:

#
# defaults:
#   - scope:
#       path: ""
#       type: trails
#     values:
#       layout: trail
