mapbox_token: "pk.eyJ1IjoibW9zc2xleWhlcml0YWdlIiwiYSI6ImNqeDFzOGk2MDBjMWgzeW1xYXZ3cjA5eTgifQ.wDNyjGwJn0ZEof6REf-xVQ"
mapbox_style: "mapbox://styles/mossleyheritage/cjx1t82kj053c1cpaoaupfxfh"
google_analytics_code: UA-121415406-1

collections_dir: collections

title: Mossley Heritage
description: Mossley is a typical former mill town for the wool and cotton industry. Discover how it grew from a hamlet with otters and eagles in the valley bottom to the thriving town it is today.

collections:
  goose:
    output: true
    permalink: /trails/gooses-gander/stops/:title
  dog:
    output: true
    permalink: /trails/dogs-life/stops/:title
  crow:
    output: true
    permalink: /trails/crow-flies/stops/:title
  bat:
    output: true
    permalink: /trails/bats-eye-view/stops/:title
  horse:
    output: true
    permalink: /trails/horses-tale/stops/:title

defaults:
  - scope:
      path: ""
      type: "bat"
    values:
      layout: "stop"
      scheme: "bat"
      trail_name: "A Bat's Eye View"
  - scope:
      path: ""
      type: "crow"
    values:
      layout: "stop"
      scheme: "crow"
      trail_name: "As the Crow Flies"
  - scope:
      path: ""
      type: "dog"
    values:
      layout: "stop"
      scheme: "dog"
      trail_name: "A Dog's Life"
  - scope:
      path: ""
      type: "goose"
    values:
      layout: "stop"
      scheme: "goose"
      trail_name: "A Goose's Gander"
  - scope:
      path: ""
      type: "horse"
    values:
      layout: "stop"
      scheme: "horse"
      trail_name: "A Horse's Tale"
